import * as fgui from "panorama-fgui-types/fgui/FairyGUI";
import { BaseView } from "../BaseView";

export const __mainhud_Data : string = "RkdVSQAAAAYAAAhiZndyZXJ6OAAHbWFpbmh1ZAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAaAAAAHgAABewAAAAAAAAF7gAAAAAAAAAAAAwAAAFqAwAAAAEAAv/+AAAAADQAAAA0DAAAAU8IAAAAACIAAAA4AAAAXAAAASYAAAEuAAABQQAAAUMAAAAAAAAANAAAADQAAT8AAAA/AAAAAAAAAAABACADAQAIAAsAHgADAAAEAAQABQAGAAcACAAJAAoACwAAAAACAFMHAQAQAD0AQQBDAAAARABTBP/+//4ADAANAAAAAAAAAAABAAAANAAAADQAAAAAP4AAAAAAAAABAQAAAP/+//7//wAAAP/+AQEEAAEAAQAAAAAAAABxBwEAEAA9AEEAQwAAAEsAbwb//v/+AA4ADwAAAAAAAAAfAQAAADQAAAAiAAAAAD+AAAAAAAAAAQEAAAD//v/+//8AAAEAAAIDAAkA//4AGP////8AAAADAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAA//4BAAACDgAPAP/+Af////4AAAAAAAAAAP/+//4AAAD//j+AAAACP0zMzf/+AAAAAAAYAAAQABEAEgATAAAAAIAAAACAAAH//gAAAAAAGAAAFAAVABIAFgAAAACAAAAAgAAB//4AAAAAABgAABcAGAASABkAAAAAgAAAAIAAAf/+AAAAAAAYAAAaABsAEgAcAAAAAIAAAACAAAH//gAAAAAAGAAAHQAeABIAHwAAAACAAAAAgAAB//4AAAAAABgAACAAIQASACIAAAAAgAAAAIAAAf/+AAAAAAMuAwAjACQAJf/+AQAAB4AAAAQ4AAAAAxMIAAAAACIAAAAvAAAASwAAAv0AAAL+AAADEQAAAAAAAAAAAAAHgAAABDgAAAAAAAABABgDAQAIAAsAFgAmAAACAAT//QAG//0AAAAABwBqBwEAEAA9AEEATQBOAFQAVAkAAP/+ACcAKAAAA5gAAAOtAQAAAIAAAACAAAAAAD+AAAAAAAAAAQEAAAD//v/+AAYAAQAIAAAAAAEABgAA//8AAAAADAAp//4AKv/+AAAAAAD////+//4AAABgBwEAEAA9AEEAQwBEAEoASgkAAP/+ACsALAAABAkAAAOtAQAAAIAAAACAAAAAAD+AAAAAAAAAAQEAAAD//v/+AAYAAAD//wAAAAAMAC3//gAu//4AAAAAAP////7//gAAAGAHAQAQAD0AQQBDAEQASgBKCQAA//4ALwAwAAAEgAAAA60BAAAAgAAAAIAAAAAAP4AAAAAAAAABAQAAAP/+//4ABgAAAP//AAAAAAwAMf/+ADL//gAAAAAA/////v/+AAAAYAcBABAAPQBBAEMARABKAEoJAAD//gAMADMAAAT/AAADrQEAAACAAAAAgAAAAAA/gAAAAAAAAAEBAAAA//7//gAGAAAA//8AAAAADAA0//4ANf/+AAAAAAD////+//4AAABgBwEAEAA9AEEAQwBEAEoASgkAAP/+AA4ANgAABYIAAAOtAQAAAIAAAACAAAAAAD+AAAAAAAAAAQEAAAD//v/+AAYAAAD//wAAAAAMADf//gA4//4AAAAAAP////7//gAAAGAHAQAQAD0AQQBDAEQASgBKCQAA//4AOQA6AAAGBwAAA60BAAAAgAAAAIAAAAAAP4AAAAAAAAABAQAAAP/+//4ABgAAAP//AAAAAAwAO//+ADz//gAAAAAA/////v/+AAAAWAcBABAAPQBBAEMAAABLAFgF//7//gA9AD4AAAOYAAADrQEAAALvAAAAgAAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAB//8CBgANAAAAAAAAAAAAAAAA//8A//4B/////gAAAAAAAAAA//7//gAA//4AAAAAACwAAD8AQAASAEEBAAAAbAAAAGwBAAAAGwAAABsAAAA2AAAANgAAAAAB//4AAAAAABgAAEIAQwASAEQBAAADnAAAAZYAAf/+AAAAAAAYAABFAEYAEgBHAQAAAFAAAABQAAH//gAAAAAAGAAASABJABIASgEAAACCAAAAggAB//4AAAAAAAAASwAHYzJuNzE3eQAMRnVuY3Rpb25JY29uAAwvY29tcG9uZW50cy8ABmJ1dHRvbgABMAACdXAAATEABGRvd24AATIABG92ZXIAATMADHNlbGVjdGVkT3ZlcgAHbjNfYzJuNwAEaWNvbgAHbjRfYzJuNwAFdGl0bGUABmMybjdvMQAOaWNuX3Rhc2tfdHlwZTQACi90ZXh0dXJlcy8ACmMybjdvMS5wbmcABmMybjdvMgAOaWNuX3Rhc2tfdHlwZTUACmMybjdvMi5wbmcABmMybjdvMwAOaWNuX3Rhc2tfdHlwZTYACmMybjdvMy5wbmcABmMybjdvNAAOaWNuX3Rhc2tfdHlwZTcACmMybjdvNC5wbmcABmMybjdvNQAOaWNuX3Rhc2tfdHlwZTgACmMybjdvNS5wbmcABmMybjdvNgAOaWNuX3Rhc2tfdHlwZTkACmMybjdvNi5wbmcABWMybjcwAAdtYWluaHVkAAcvdmlld3MvAARzaG93AAduMF9jMm43AAdyb2xlQnRuAAzop5LoibLkv6Hmga8AE3VpOi8vYmZ3cmVyejhjMm43bzYAB24xX2MybjcAAm4xAAbngrzkuLkAE3VpOi8vYmZ3cmVyejhjMm43bzUAB24yX2MybjcABmJhZ0J0bgAG6IOM5YyFABN1aTovL2Jmd3Jlcno4YzJuN280AAJuMwAG5Lqk5piTABN1aTovL2Jmd3Jlcno4YzJuN28zAAJuNAAJ5ouN5Y2W6KGMABN1aTovL2Jmd3Jlcno4YzJuN28yAAduNV9jMm43AAJuNQACUEsAE3VpOi8vYmZ3cmVyejhjMm43bzEAB242X2MybjcAAm42AAZjMm43OGIAAkJHAApjMm43OGIucG5nAAZjMm43OGcACGJnX2Z1YmVuAApjMm43OGcucG5nAAZjMm43OXIACGJ0bkNsb3NlAApjMm43OXIucG5nAAZjMm43eGMACHNlbGVjdGJnAApjMm43eGMucG5n";

export class mainhud_mainhud_data extends BaseView{
	public show : fgui.Controller;
	public roleBtn : fgui.GComponent;
	public n1 : fgui.GComponent;
	public bagBtn : fgui.GComponent;
	public n3 : fgui.GComponent;
	public n4 : fgui.GComponent;
	public n5 : fgui.GComponent;
	public n6 : fgui.GGroup;
    constructor()
    {
        super();
        this.package = "mainhud";
        this.packageItem = "mainhud";
        this.binData = __mainhud_Data;

        this.OnInit();
    }

    public OnInit():void
    {
        super.OnInit();
		this.show = this.getController("show");
		this.roleBtn = <fgui.GComponent><unknown>(this.getChild("roleBtn"));
		this.n1 = <fgui.GComponent><unknown>(this.getChild("n1"));
		this.bagBtn = <fgui.GComponent><unknown>(this.getChild("bagBtn"));
		this.n3 = <fgui.GComponent><unknown>(this.getChild("n3"));
		this.n4 = <fgui.GComponent><unknown>(this.getChild("n4"));
		this.n5 = <fgui.GComponent><unknown>(this.getChild("n5"));
		this.n6 = <fgui.GGroup><unknown>(this.getChild("n6"));
    }
}

