import * as fgui from "panorama-fgui-types/fgui/FairyGUI";
import { BaseView } from "../BaseView";
import { BinCache } from "../BinCache";
export class uipublic_itemcell_data extends fgui.GButton{
	public button_c : fgui.Controller;
	public empty_c : fgui.Controller;
	public n5 : fgui.GLoader;
	public qualityLoader : fgui.GLoader;
	public item : fgui.GDOTAItemImage;
	public n6 : fgui.GLoader;

    protected onConstruct():void
    {
        this.panelName = "uipublic_itemcell";
		this.button_c = this.getController("button");
		this.empty_c = this.getController("empty");
		this.n5 = <fgui.GLoader><unknown>(this.getChild("n5"));
		this.qualityLoader = <fgui.GLoader><unknown>(this.getChild("qualityLoader"));
		this.item = <fgui.GDOTAItemImage><unknown>(this.getChild("item"));
		this.n6 = <fgui.GLoader><unknown>(this.getChild("n6"));
    }
}


BinCache.PrecachePackage("uipublic", "RkdVSQAAAAYAAAh3ZHJjZDhycAAIdWlwdWJsaWMAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAGgAAACIAAALPAAAAAAAAAtEAAAAAAAEAAAABAAAABQAAAiMDAAIAAwAE//4BAAAAZAAAAGQMAAACCAgAAAAAIgAAAC8AAABlAAAB5gAAAecAAAH6AAAB/AAAAAAAAABkAAAAZAAAAAAAAAIAGAMBAAgACwAWAAUAAAIABgAHAAgACQAAAAAYAwEACAALABYACgAAAgAG//0ACP/9AAAAAAQAaAcBABAAPQBBAE0AAABZAGgE//7//gALAAz////x////8QEAAACEAAAAhAAAAAA/gAAAAAAAAAEBAAAA//7//v//AAEACAAAAAABAAgAAf//BA4ADwADAAoAAA0AAAQAAAABAAAAAAAAAFoHAQAQAD0AQQBDAAAASwBaBP/+//4ADgAPAAAAAAAAAAABAAAAZAAAAGQAAAAAP4AAAAAAAAABAQAAAP/+//7//wAAAf//Ag4ADwD//gAABAAAAAEAAAAAAAAAUQcBABAAPQBBAEMASwBRAFEJABAAAAARABIAAAAAAAAAAAEAAABkAAAAZAAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAB//8CDgAPAP//AAAAAABkBwEAEAA9AEEATQAAAFUAZAT//v/+ABMAFAAAAAAAAAAAAQAAAGQAAABkAAAAAD+AAAAAAAAAAQEAAAD//v/+//8AAQAIAAABAAEACAAB//8CDgAPAAAVAAAEAAAAAQAAAAAAAAD//gH////+AAAAAAAAAAD//v/+AAAC//4/gAAAAD9MzM3//gAAAAAAGAAAFgAXABgAGQEAAABPAAAAUQAB//4AAAAAABgAABoAGwAYABwBAAAAUAAAAHwAAf/+AAAAAAAYAAAdAB4AGAAfAQAAAeAAAAFOAAH//gAAAAAALAAAIAAhABgAIgEAAAAUAAAAFAEAAAAFAAAABQAAAAoAAAAKAAAAAAH//gAAAAAAAAAjAAg0djB2bGZxOQAJZG90YXBhbmVsAAVjMm43MQAIaXRlbWNlbGwADC9jb21wb25lbnRzLwAGYnV0dG9uAAEwAAJ1cAABMQAEZG93bgAFZW1wdHkAB241X2MybjcAAm41ABN1aTovL3dkcmNkOHJwanJsNjFnAAduM19jMm43AA1xdWFsaXR5TG9hZGVyAAVrNDB2NAAHbjJfYzJuNwAEaXRlbQAHbjZfZ29hZgACbjYAEnVpOi8vNHYwdmxmcTlkbjN2NwAGanJsNjFnAAtnZ19jaGF0X3NlbAAKL3RleHR1cmVzLwAKanJsNjFnLnBuZwAGanJsNjFrAAtnZ19jbG9zZV8wMwAKanJsNjFrLnBuZwAFanJsNjYACmdnX3RzYmdfMDEACWpybDY2LnBuZwAFanJsNjkADGdnX3hpYW9kaV8wMQAJanJsNjkucG5n");
