import * as fgui from "panorama-fgui-types/fgui/FairyGUI";
import { BaseView } from "../BaseView";
import { BinCache } from "../BinCache";
export class mainhud_mainhud_data extends BaseView{
	public show_c : fgui.Controller;
	public roleBtn : fgui.GComponent;
	public n1 : fgui.GComponent;
	public bagBtn : fgui.GComponent;
	public n3 : fgui.GComponent;
	public n4 : fgui.GComponent;
	public n5 : fgui.GComponent;
	public n6 : fgui.GGroup;
    constructor()
    {
        super();
        this.package = "mainhud";
        this.packageItem = "mainhud";

        this.OnInit();
    }

    public OnInit():void
    {
        super.OnInit();
		this.show_c = this.getController("show");
		this.roleBtn = <fgui.GComponent><unknown>(this.getChild("roleBtn"));
		this.n1 = <fgui.GComponent><unknown>(this.getChild("n1"));
		this.bagBtn = <fgui.GComponent><unknown>(this.getChild("bagBtn"));
		this.n3 = <fgui.GComponent><unknown>(this.getChild("n3"));
		this.n4 = <fgui.GComponent><unknown>(this.getChild("n4"));
		this.n5 = <fgui.GComponent><unknown>(this.getChild("n5"));
		this.n6 = <fgui.GGroup><unknown>(this.getChild("n6"));
    }
}


BinCache.PrecachePackage("mainhud", "RkdVSQAAAAYAAAhiZndyZXJ6OAAHbWFpbmh1ZAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAaAAAAHgAABMAAAAAAAAAEwgAAAAAAAAAAAAIAAAFqAwAAAAEAAv/+AAAAADQAAAA0DAAAAU8IAAAAACIAAAA4AAAAXAAAASYAAAEuAAABQQAAAUMAAAAAAAAANAAAADQAAT8AAAA/AAAAAAAAAAABACADAQAIAAsAHgADAAAEAAQABQAGAAcACAAJAAoACwAAAAACAFMHAQAQAD0AQQBDAAAARABTBP/+//4ADAANAAAAAAAAAAABAAAANAAAADQAAAAAP4AAAAAAAAABAQAAAP/+//7//wAAAP/+AQEEAAEAAQAAAAAAAABxBwEAEAA9AEEAQwAAAEsAbwb//v/+AA4ADwAAAAAAAAAfAQAAADQAAAAiAAAAAD+AAAAAAAAAAQEAAAD//v/+//8AAAEAAAIDAAkA//4AGP////8AAAADAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAA//4BAAACDgAPAP/+Af////4AAAAAAAAAAP/+//4AAAD//j+AAAACP0zMzf/+AAAAAAMuAwAQABEAEv/+AQAAB4AAAAQ4AAAAAxMIAAAAACIAAAAvAAAASwAAAv0AAAL+AAADEQAAAAAAAAAAAAAHgAAABDgAAAAAAAABABgDAQAIAAsAFgATAAACAAT//QAG//0AAAAABwBqBwEAEAA9AEEATQBOAFQAVAkAAP/+ABQAFQAAA5gAAAOtAQAAAIAAAACAAAAAAD+AAAAAAAAAAQEAAAD//v/+AAYAAQAIAAAAAAEABgAA//8AAAAADAAW//4AF//+AAAAAAD////+//4AAABgBwEAEAA9AEEAQwBEAEoASgkAAP/+ABgAGQAABAkAAAOtAQAAAIAAAACAAAAAAD+AAAAAAAAAAQEAAAD//v/+AAYAAAD//wAAAAAMABr//gAb//4AAAAAAP////7//gAAAGAHAQAQAD0AQQBDAEQASgBKCQAA//4AHAAdAAAEgAAAA60BAAAAgAAAAIAAAAAAP4AAAAAAAAABAQAAAP/+//4ABgAAAP//AAAAAAwAHv/+AB///gAAAAAA/////v/+AAAAYAcBABAAPQBBAEMARABKAEoJAAD//gAMACAAAAT/AAADrQEAAACAAAAAgAAAAAA/gAAAAAAAAAEBAAAA//7//gAGAAAA//8AAAAADAAh//4AIv/+AAAAAAD////+//4AAABgBwEAEAA9AEEAQwBEAEoASgkAAP/+AA4AIwAABYIAAAOtAQAAAIAAAACAAAAAAD+AAAAAAAAAAQEAAAD//v/+AAYAAAD//wAAAAAMACT//gAl//4AAAAAAP////7//gAAAGAHAQAQAD0AQQBDAEQASgBKCQAA//4AJgAnAAAGBwAAA60BAAAAgAAAAIAAAAAAP4AAAAAAAAABAQAAAP/+//4ABgAAAP//AAAAAAwAKP/+ACn//gAAAAAA/////v/+AAAAWAcBABAAPQBBAEMAAABLAFgF//7//gAqACsAAAOYAAADrQEAAALvAAAAgAAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAB//8CBgANAAAAAAAAAAAAAAAA//8A//4B/////gAAAAAAAAAA//7//gAA//4AAAAAAAAALAAHYzJuNzE3eQAMRnVuY3Rpb25JY29uAAwvY29tcG9uZW50cy8ABmJ1dHRvbgABMAACdXAAATEABGRvd24AATIABG92ZXIAATMADHNlbGVjdGVkT3ZlcgAHbjNfYzJuNwAEaWNvbgAHbjRfYzJuNwAFdGl0bGUABWMybjcwAAdtYWluaHVkAAcvdmlld3MvAARzaG93AAduMF9jMm43AAdyb2xlQnRuAAzop5LoibLkv6Hmga8AE3VpOi8vYmZ3cmVyejhjMm43bzYAB24xX2MybjcAAm4xAAbngrzkuLkAE3VpOi8vYmZ3cmVyejhjMm43bzUAB24yX2MybjcABmJhZ0J0bgAG6IOM5YyFABN1aTovL2Jmd3Jlcno4YzJuN280AAJuMwAG5Lqk5piTABN1aTovL2Jmd3Jlcno4YzJuN28zAAJuNAAJ5ouN5Y2W6KGMABN1aTovL2Jmd3Jlcno4YzJuN28yAAduNV9jMm43AAJuNQACUEsAE3VpOi8vYmZ3cmVyejhjMm43bzEAB242X2MybjcAAm42");
