import * as fgui from "panorama-fgui-types/fgui/FairyGUI";
import { BaseView } from "../BaseView";

export const __package1_Data : string = "RkdVSQAAAAYAAAhyYncxdHY5dAAIcGFja2FnZTEAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAGgAAACIAAB++AAAAAAAAH8AAAAAAAAEAAAABAAAADwAAAqQDAAIAAwAE//4AAAAAyAAAAB4MAAACiQgAAAAAIgAAAC8AAABLAAACZwAAAmgAAAJ7AAACfQAAAAAAAADIAAAAHgAAAAAAAAEAGAMBAAgACwAWAAUAAAIABgAHAAgACQAAAAAEAFIHAQAQAD0AQQBDAAAARABSA//+//4ACgALAAAAAAAAAAABAAAAyAAAAB4AAAAAP4AAAAAAAAABAQAAAP/+//7//wAAAAEAAAABAAAA/2ZmZv8AAJIHAQAQAD0AQQCDAAAAhACSA//+//4ADAANAAAAAAAAAAABAAAAMgAAAB4AAAAAP4AAAAAAAAABAQAAAP/+//7//wACACMBAAAAAQAIAAAAbAAAAAABAAAAAAAAAAABBT6ZmZoAAAAAAAAZBAAAAAEACDMzzP8AAAD/AQCZ//8AAAD/AAABAAAAAQAAAP8Amf//AADVBwEAEAA9AEEAxgAAAMcA1QP//v/+AA4ADwAAAJYAAAAAAQAAADIAAAAeAAAAAD+AAAAAAAAAAQEAAAD//v/+//8AAwAlAQAAAAIABgAAAJYAAAAAAAgAAAATAAAAAAABBT6ZmZoAAAAAAAAyAgAAAAEACAAAADIAAAAePszMzT8AAAABAAAAMgAAAB4/gAAAP4AAAAEFPpmZmgAAAAAAJgMAAAABAAgAAAAAAAAAAAABAT+AAAAAAAAAAAEBBT6ZmZoAAAAAAAEAAAABAAAA//8AAP8AAFkHAQAQAD0AQQBDAAAASwBZA//+//4AEAARAAAAMv///9sBAAAAJgAAAGQAAAAAP4AAAAAAAAABAQAAAP/+//7//wAAAQABAgoAAgABAAAAAQAAAP//////AAD//gH////+AAAAAAAAAAD//v/+AAAB//4/gAAAAD9MzM3//gAAAAABjQMAEgATABT//gAAAAAyAAAACg4AAAFyCAAAAAAiAAAALwAAADEAAAFaAAABWwAAAW4AAAFwAAAAAAAAADIAAAAKAAAAAAAAAAADAFkHAQAQAD0AQQBDAAAASwBZA//+//4AFQALAAAAAAAAAAABAAAAMgAAAAoAAAAAP4AAAAAAAAABAQAAAP/+//7//wAAAf//Ag4ADwABAAAAAaCgoP/w8PD/AABXBwEAEAA9AEEAQwAAAEkAVwP//v/+ABYAFwAAAAAAAAADAQAAADIAAAAEAAAAAD+AAAAAAAAAAQEAAAD//v/+//8AAAH//wEPAAEAAAAAAAAA/zOZ//8AAHEHAQAQAD0AQQBDAAAASwBvBv/+//4AGAAZAAAAAP////QBAAAAMgAAAAoAAAAAP4AAAAAAAAABAQAAAP/+//7//wAAAf//Ag4ADwD//gAYAAAA/wEBAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//gD//gH////+AAAAAAAAAAD//v/+AAABAP/+AAAAAAIeAwAaABsABP/+AAAAAMgAAAAeDAAAAgMIAAAAACIAAAAvAAAASwAAAeEAAAHiAAAB9QAAAfcAAAAAAAAAyAAAAB4AAAAAAAABABgDAQAIAAsAFgAFAAACAAYABwAIAAkAAAAABABcBwEAEAA9AEEATQAAAE4AXAP//v/+AAoACwAAAAAAAAAAAQAAAMgAAAAeAAAAAD+AAAAAAAAAAQEAAAD//v/+//8AAQAIAAAAAAEACAAAAQAAAAEAAAD/AGYA/wAAXAcBABAAPQBBAE0AAABOAFwD//7//gAcAB0AAAAAAAAAAAEAAADIAAAAHgAAAAA/gAAAAAAAAAEBAAAA//7//v//AAEACAAAAAABAAYAAAEAAAABAAAA/5n/M/8AAGoHAQAQAD0AQQBDAAAARABoBv/+//4AHgAfAAAACgAAAAYBAAAANAAAABMAAAAAP4AAAAAAAAABAQAAAP/+//7//wAAAP/+AAwAAAD/AAAAAwAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAGoHAQAQAD0AQQBDAAAARABoBv/+//4AIQAiAAAAjQAAAAYBAAAAKAAAABMAAAAAP4AAAAAAAAABAQAAAP/+//7//wAAAP/+AAwAAAD/AgAAAwAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAjAP/+Af////4AAAAAAAAAAP/+//4AAAL//j+AAAAAP0zMzf/+AAAAAAFpAwAkACUABP/+AAAAAGQAAAAUDAAAAU4IAAAAACIAAAA4AAAAXAAAASwAAAEtAAABQAAAAUIAAAAAAAAAZAAAABQAAT8AAAA/AAAAAAAAAAABACADAQAIAAsAHgAFAAAEAAYABwAIAAkAJgAnACgAKQAAAAACAFkHAQAQAD0AQQBDAAAASwBZA//+//4AKgALAAAAAAAAAAABAAAAZAAAABQAAAAAP4AAAAAAAAABAAAAAP/+//7//wAAAf//Ag4ADwABAAAAAAAAAP8AZsz/AABxBwEAEAA9AEEAQwAAAEsAbwb//v/+ACsAGQAAAAD////5AQAAAGQAAAAiAAAAAD+AAAAAAAAAAQEAAAD//v/+//8AAAH//wIOAAoA//4AGAAAAP8BAQADAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAA//4A//4B/////gAAAAAAAAAA//7//gAAAP/+P4AAAAI/TMzN//4AAAAAAO0DACwALQAU//4AAAAACgAAABMMAAAA0ggAAAAAIgAAAC8AAABTAAAAsAAAALEAAADEAAAAxgAAAAAAAAAKAAAAEwAAAAAAAAEAIAMBAAgACwAeAAUAAAQABgAHAAgACQAmACcAKAApAAAAAAEAWQcBABAAPQBBAEMAAABLAFkD//7//gAqAAsAAAAAAAAAAAEAAAAKAAAAEwAAAAA/gAAAAAAAAAEAAAAA//7//v//AAAB//8CDgAPAAEAAAAAAAAA//Dw8P8AAP/+Af////4AAAAAAAAAAP/+//4AAAD//j+AAAAAP0zMzf/+AAAAAAFgAwAuAC8AFP/+AAAAADIAAAAKDwAAAUUIAAAAACIAAAAvAAAAMQAAASsAAAEsAAABPwAAAUEAAAAAAAAAMgAAAAoAAAAAAAAAAAMAWQcBABAAPQBBAEMAAABLAFkD//7//gAqAAsAAAAAAAAAAAEAAAAyAAAACgAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAB//8CDgAPAAEAAAABoKCg//Dw8P8AAFIHAQAQAD0AQQBDAAAARABSA//+//4AMAAXAAAABQAAAAMBAAAAKAAAAAQAAAAAP4AAAAAAAAABAQAAAP/+//7//wAAAAEAAAAAAAAA/zOZ//8AAEcHAQAQADUAOQA7AEEARwBHCQAs//4AMQAyAAAAKP////sAAAAAAD+AAAAAAAAAAQEAAAD//v/+//8AAAEAAQEGAP//AAAAAAD//gH////+AAAAAAAAAAD//v/+AAAAAAAB//4AAAAAAdMDADMANAAU//4AAAAAZAAAABQMAAABuAgAAAAAIgAAAC8AAABTAAABlgAAAZcAAAGqAAABrAAAAAAAAABkAAAAFAAAAAAAAAEAIAMBAAgACwAeAAUAAAQABgAHAAgACQAmACcAKAApAAAAAAMAYwcBABAAPQBBAE0AAABVAGMD//7//gAqAAsAAAAAAAAAAAEAAABkAAAAFAAAAAA/gAAAAAAAAAEAAAAA//7//v//AAEACAAAAAABACYAAf//Ag4ADwABAAAAAQAAAP8zmf//AABnBwEAEAA9AEEAUQAAAFkAZwP//v/+ADAAHQAAAAAAAAAAAQAAAGQAAAAUAAAAAD+AAAAAAAAAAQAAAAD//v/+//8AAQAMAAAAAAMABgAIACgAAf//Ag4ADwABAAAAAQAAAP//mTP/AABxBwEAEAA9AEEAQwAAAEsAbwb//v/+ADEAGQAAAAAAAAAAAQAAAGQAAAAUAAAAAD+AAAAAAAAAAQEAAAD//v/+//8AAAH//wIOAA8A//4ADAAAAP8AAQADAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAA//4A//4B/////gAAAAAAAAAA//7//gAAAv/+P4AAAAA/TMzN//4AAAAAAUMDADUANgAU//4AAAAAlgAAAMgAAAABKAgAAAAAIgAAAC8AAAAxAAABDQAAARMAAAEmAAAAAAAAAAAAAACWAAAAyAAAAAAAAAAAAgBZBwEAEAA9AEEAQwAAAEsAWQP//v/+ACoACwAAAAAAAAAAAQAAAJYAAADIAAAAAD+AAAAAAAAAAQAAAAD//v/+//8AAAH//wIOAA8AAQAAAAMzMzP/8PDw/wAAfQkBABQAQQBFAEcATQBTAGgAagB5Cv/+//4AMAA3AAAAAAAAAAABAAAAlgAAAMgAAAAAP4AAAAAAAAABAQAAAP/+//7//wAAAf//AQ4A//8AAAAAAAAAAAAFAAAAAAAAAQAAAAACAAEA//8BAAAAAAAA//7//v/+//4AOAAAAQABAQ8A//4B/////gAAAAAAAAAA//7//gAA//4AAAAAAeADADkAOgAU//4BAAAHgAAABDgAAAABxQgAAAAAIgAAAC8AAAAxAAABrwAAAbAAAAHDAAAAAAAAAAAAAAeAAAAEOAAAAAAAAAAAAwBfBwEAEAA9AEEAQwBEAEoASgkAO//+ADwAPQAAAGgAAALBAQAAAV4AAABCAAAAAD+AAAAAAAAAAQEAAAD//v/+//8AAAD//wAAAAANAAD//v/+AAAAAAoA/////j+AAAAAVwcBABAAPQBBAEMARABKAEoJAC7//gA+AD8AAABgAAACWwEAAAFZAAAACgAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAA//8AAAAADwAAADIAAABkAAAAAADACQEAFABBAEUARwBIAE4AYwBlAHQK//7//gBAAEEAAAQLAAAAhQEAAACBAAAA+AAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAA//8AAAAAAAAAAAAFAAAAAAAAAAAAAAACAAEA//8BAAAAAAAA//7//v/+//4AQgAEABD//v/+//7//v/+//4AAAAAABD//v/+//7//v/+//4AAAAAABD//v/+//7//v/+//4AAAAAABD//v/+//7//v/+//4AAAAAAP/+Af////4AAAAAAAAAAP/+//4AAP/+AAAAAAcBAwBDAEQAFP/+AQAAB4AAAAQ4AAAABuYIAAAAACIAAAAvAAAAMQAABtAAAAbRAAAG5AAAAAAAAAAAAAAHgAAABDgAAAAAAAAAABIAQgcBABAANQA5ADsAPABCAEIJAEUAAABGAEcAAAB5AAAAewAAAAAAP4AAAAAAAAABAQAAAP/+//7//wAAAP//AAAAAABKBwEAEAA9AEEAQwBEAEoASgkASAAAAEkASgAAAJ8AAAEaAQAAAGQAAABkAAAAAD+AAAAAAAAAAQEAAAD//v/+//8AAAD//wAAAAAASgcBABAAPQBBAEMARABKAEoJAEsAAAAMAEwAAACfAAABkgEAAABkAAAAZAAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAA//8AAAAAAEoHAQAQAD0AQQBDAEQASgBKCQBNAAAADgBOAAAAnwAAAgoBAAAAZAAAAGQAAAAAP4AAAAAAAAABAQAAAP/+//7//wAAAP//AAAAAABKBwEAEAA9AEEAQwBEAEoASgkATwAAAFAAUQAAAJ8AAAKCAQAAAGQAAABkAAAAAD+AAAAAAAAAAQEAAAD//v/+//8AAAD//wAAAAAASgcBABAAPQBBAEMARABKAEoJAFIAAABTAFQAAACfAAADcgEAAABkAAAAZAAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAA//8AAAAAAEIHAQAQADUAOQA7ADwAQgBCCQAC//4AVQBWAAADpQAAATwAAAAAAD+AAAAAAAAAAQEAAAD//v/+//8AAAD//wAAAAAAnwcBABAAPQBBAEMARABKAEoJADv//gBXAFgAAAOzAAABnwEAAACrAAAALwAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAA//8AAAAADQAIAAYAWf/+//4ABgBa//7//gAGAFv//v/+AAYAXP/+//4ABgBd//7//gAGAF7//v/+AAYAX//+//4ABgBg//7//gBh//4AAAAACgD////+P4AAAAB3BwEAEAA9AEEAQwBEAFEAdQj//v/+AGIAYwAAA7kAAAHxAQAAALwAAAA+AAAAAD+AAAAAAAAAAQEAAAD//v/+//8AAAAAZP/+AAAAAAAAAAAB//4ADAAAAP8AAAADAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGUAagcBABAAPQBBAEMAAABEAGgH//7//gBmAGcAAALIAAACtAEAAAJ/AAAALQAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAA//4AGABmmf8CAgADAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGgAagcBABAAPQBBAEMAAABEAGgG//7//gBpAGoAAAMsAAADqgEAAAIzAAAAdAAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAA//4AGABmmf8CAgADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGsAcgcBABAAPQBBAEMAAABEAHAG//7//gBsAG0AAAF0AAAA4gEAAAMFAAAAIgAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAA//4AGABmmf8CAAADAAAAAwAAAAAB/////z+AAAAAAAAAAAAAAAAAAAAAAAAAbgB4CQEAFABBAEUARwBIAE4AYwBlAHQK//7//gBvADcAAAWvAAAAgAEAAAEKAAABMAAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAA//8AAAAAAAAAAAAUAAAAAAAAAQAAAAACAAEA//8BAAAAAAAA//7//v/+//4AcAAAAFcHAQAQAD0AQQBDAEQASgBKCQAu//4AcQByAAACNQAAAfEBAAAA4wAAAAoAAAAAP4AAAAAAAAABAQAAAP/+//7//wAAAP//AAAAAA8AAAAyAAAAZAAAAAAARwcBABAAPQBBAEMAAABEAEcAAHP//gB0AHUAAACmAAAAIgEAAABkAAAAZAAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAAAAAAAFoHAQAQAEYASgBMAFQAWgBaCQB2AAAAdwB4AAAA2AAAAFQBAAAAZAAAAGQAAAABPwAAAD8AAAABP4AAAAAAAAABAQAAAP/+//7//wAAAQAAAgMACgD//wAAAAAAWgcBABAARgBKAEwAVABaAFoJAHYAAAB5AHoAAAC2AAAAvgEAAABkAAAAZAAAAAE/AAAAPwAAAAE/gAAAAAAAAAEAAAAA//7//v//AAABAAACAwAKAP//AAAAAABdBwEAEAA9AEEAQwBEAEoASgkAEv/+AHsAfAAAAWMAAAOVAQAAAXkAAAB5AAAAAD+AAAAAAAAAAQEAAAD//v/+//8AAAD//wAAAAAOAAAAMgAAAGQAAAAA//4/gAAAAP/+Af////4AAAAAAAAAAP/+//4AAP/+AAAAAAQaAwB9AH4AFP/+AQAAB4AAAAQ4AAAAA/8IAAAAACIAAAAvAAAAMQAAAx4AAAMfAAADMgAAAAAAAAAAAAAHgAAABDgAAAAAAAAAAAUAZwcBABAANQA5ADsAPABCAEIJADv//gB/AIAAAADsAAAAxgAAAAAAP4AAAAAAAAABAQAAAP/+//7//wAAAP//AAAAAA0AAgAGAIH//v/+AAYAgv/+//4Ag//+AAAAAAoA/////j+AAAAAVwcBABAAPQBBAEMARABKAEoJAC7//gA8AD0AAAEOAAABjwEAAAFPAAAACgAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAA//8AAAAADwAAADIAAABkAAAAAAGGCQEAFABBAEUARwBIAE4AYwBlAHQK//7//gCEAD8AAABwAAAByQEAAAFfAAABUQAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAA//8AAAAAAAAAAAAFAAAAAAAAAQAAAAACAAEA//8BAAAAAAAA//7//v/+//4AcAAPABD//v/+//7//v/+//4AAAAAABD//v/+//7//v/+//4AAAAAABD//v/+//7//v/+//4AAAAAABD//v/+//7//v/+//4AAAAAABD//v/+//7//v/+//4AAAAAABD//v/+//7//v/+//4AAAAAABD//v/+//7//v/+//4AAAAAABD//v/+//7//v/+//4AAAAAABD//v/+//7//v/+//4AAAAAABD//v/+//7//v/+//4AAAAAABD//v/+//7//v/+//4AAAAAABD//v/+//7//v/+//4AAAAAABD//v/+//7//v/+//4AAAAAABD//v/+//7//v/+//4AAAAAABD//v/+//7//v/+//4AAAAAAFsHAQAQAEYASgBMAAAATQBbA//+//4AhQBBAAAC5AAAAioBAAAAZAAAAGQAAAABPwAAAD8AAAABP4AAAAAAAAABAQAAAP/+//7//wAAAAEAAAABAAAA//////8AAEIHAQAQADUAOQA7ADwAQgBCCQAC//4AhgCHAAACxgAAAysAAAAAAD+AAAAAAAAAAQEAAAD//v/+//8AAAD//wAAAAAA//4B/////gAAAAAAAAAA//7//gABAMkAiAAAAAAB/////wAAAAAABAAsBAEACgAUACAAJAUAAAAAAAP//gE+gAAABQAAAAAA//4AAAAAQrQAAAAAAAAALAQBAAoAFAAgACQFPoAAAAAD//4BPoAAAAUAAAAAAP/+QrQAAEM0AAAAAAAAACwEAQAKABQAIAAkBT8AAAAAA//+AT6AAAAFAAAAAAD//kM0AABDhwAAAAAAAAAsBAEACgAUACAAJAU/QAAAAAP//gE+gAAABQAAAAAA//5DhwAAQ7QAAAAAAAD//gAAAAACLAMAOwCJABT//gEAAABkAAAAFA0AAAIRCAAAAAAiAAAALwAAAFMAAAH5AAAB+gAAAg0AAAIPAAAAAAAAAGQAAAAUAAAAAAAAAQAgAwEACAALAB4ABQAABAAGAAcACAAJACYAJwAoACkAAAAABABjBwEAEAA9AEEATQAAAFUAYwP//v/+ACoACwAAAAAAAAAAAQAAAGQAAAAUAAAAAD+AAAAAAAAAAQAAAAD//v/+//8AAQAIAAAAAAEABgAB//8CDgAPAAEAAAAAAAAA//Dw8P8AAGMHAQAQAD0AQQBNAAAAVQBjA//+//4AMAAdAAAAAAAAAAABAAAAZAAAABQAAAAAP4AAAAAAAAABAAAAAP/+//7//wABAAgAAAAAAQAmAAH//wIOAA8AAQAAAAAAAAD/+vr6/wAAZQcBABAAPQBBAE8AAABXAGUD//7//gAxAA0AAAAAAAAAAAEAAABkAAAAFAAAAAA/gAAAAAAAAAEAAAAA//7//v//AAEACgAAAAACAAgAKAAB//8CDgAPAAEAAAAAAAAA/8zMzP8AAHEHAQAQAD0AQQBDAAAASwBvBv/+//4AKwAZAAAAAAAAAAABAAAAUAAAABQAAAAAP4AAAAAAAAABAQAAAP/+//7//wAAAf//Ag4ADwD//gAMAAAA/wABAAMAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAD//gD//gH////+AAAAAAAAAAD//v/+AAAAiv/+AAAAAALsAwCLAIwAFP/+AQAAB4AAAAQ4AAAAAtEIAAAAACIAAAAvAAAAMQAAArsAAAK8AAACzwAAAAAAAAAAAAAHgAAABDgAAAAAAAAAAAYAagcBABAAPQBBAEMAAABEAGgG//7//gCNAAsAAAASAAAAaAEAAAK4AAAAaQAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAA//4AGAAAAP8AAAADAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI4AagcBABAAPQBBAEMAAABEAGgG//7//gCPAB0AAAATAAAA/AEAAAVEAAAAIgAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAA//4AGAAAAP8AAAADAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAJAAagcBABAAPQBBAEMAAABEAGgG//7//gCRAA0AAAARAAABkAEAAAKyAAAAhAAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAA//4AGAAAAP8AAAADAAABAgAAAAAAAAAAAAAAAAAAAAAAAAAAAJIAagcBABAAPQBBAEMAAABEAGgG//7//gCTAA8AAAARAAACQQEAAAK7AAAAaQAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAA//4AGAAAAP8AAAADAAABAwAAAAAAAAAAAAAAAAAAAAAAAAAAAJQAagcBABAAPQBBAEMAAABEAGgG//7//gCVAJYAAAATAAAC8AEAAAKyAAAAaQAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAA//4AGAAAAP8AAAADAAABBAAAAAAAAAAAAAAAAAAAAAAAAAAAAJcAagcBABAAPQBBAEMAAABEAGgH//7//gCYABEAAAASAAADowEAAAQhAAAAWwAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAA//4AGAAAAP8AAAADAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJkA//4B/////gAAAAAAAAAA//7//gAA//4AAAAAABgAAJoAKACbAJwBAAAAGAAAABgAAf/+AAAAAAAYAABzACYABACdAQAAABgAAAAYAAH//gAAAAAAAACeAAg0djB2bGZxOQAJZG90YXBhbmVsAAVhdmc2egAJdGVzdGNvbXAyAAEvAAZidXR0b24AATAAAnVwAAExAARkb3duAAduMF9hdmc2AAJuMAAHbjJfazQwdgACbjIAB24zX2s0MHYAAm4zAAduNV9pZG9jAAJuNQAGZGY1cDEzAAxQcm9ncmVzc0JhcjEABy92aWV3cy8AB24wX2RmNXAAB24xX2RmNXAAA2JhcgAHbjJfZGY1cAAFdGl0bGUABWVsbG53AAh0ZXN0Y29tcAAHbjFfYXZnNgACbjEAB24yX2lkb2MABHJhbmsADOesrOS4gOWQje+8mgAHbjNfaWRvYwAEbmFtZQAJ5pe25YWJ5py6AAV1N3phbwAHQnV0dG9uMgABMgAEb3ZlcgABMwAMc2VsZWN0ZWRPdmVyAAduMF91N3phAAduM191N3phAAV1N3phcQAMU2xpZGVyMV9ncmlwAAV1N3phcgAHU2xpZGVyMQAHbjFfdTd6YQAHbjJfdTd6YQAEZ3JpcAAFdTd6YXQADkNvbWJvQm94MV9pdGVtAAV1N3phdQAPQ29tYm9Cb3gxX3BvcHVwAARsaXN0ABJ1aTovL3JidzF0djl0dTd6YXQABWZ2YWliAAdtYWluaHVkAAV1N3phdgAHbjdfZWxsbgACbjcAB244X2VsbG4AAm44AAduOV9lbGxuAAJuOQASdWk6Ly9yYncxdHY5dHU3emFvAAZrNDB2MTAABnRlc3R1aQAFazQwdjUAB24wX2s0MHYADGFiaWxpdHlJbWFnZQAFazQwdjMAB24xX2s0MHYAC2F2YXRhckltYWdlAAVrNDB2MgAJaGVyb0ltYWdlAAVrNDB2NAAJaXRlbUltYWdlAAVrNDB2NgAHbjRfazQwdgAIdXNlck5hbWUABWs0MHYwAAduNl9rNDB2AAVtb2RlbAAHbjlfazQwdgAMdG9nZ2xlQnV0dG9uAAhuMTBfazQwdgAIZHJvcGRvd24AAzMzMwADNDQ0AAI1NQADNjY2AAFhAAFiAAFjAAFkAAnkuIvmi4nmoYYACG4xMV9xMWRrAAVpbnB1dAAM6L6T5YWl5o+Q56S6AAcxMjMyMTMyAAhuMTJfcTFkawAHcmljaGJveACGMVtiXTIzWy9iXTIxMzJbaV0xMzEyWy9pXTMyMVtjb2xvcj0jMDBjYzk5XTIxW3VdMzIxWy91XTMyMVsvY29sb3JdW3NpemU9MzNdaGZnZGZbL3NpemVd5rSS5rC05aSn5omA5aSn5omAW2ltZ111aTovL3JidzF0djl0b2h4YW1bL2ltZ10ACG4xM19xMWRrAANuMTMAb+WViuWViuaSkuaSkuaJk+eul+Wlpeacr+Wkp+W4iOWkp+aJgOWkp+Wkp+aJgOWkp+aJgOWkmuWViuWViuaSkuaSkuaJk+eul+Wlpeacr+Wkp+W4iOWkp+aJgOWkp+Wkp+aJgOWkp+aJgOWkmuWVigAIbjE0X3ExZGsAA24xNAC05pKS5pKS5omT566Xc2Fk5pKS5pKS5omT566Xc2Fk5pKS5pKS5omT566Xc2Fk5pKS5pKS5omT566Xc2Fk5pKS5pKS5omT566Xc2Fk5pKS5pKS5omT566Xc2Fk5pKS5pKS5omT566Xc2Fk5pKS5pKS5omT566Xc2Fk5pKS5pKS5omT566Xc2Fk5pKS5pKS5omT566Xc2Fk5pKS5pKS5omT566Xc2Fk5pKS5pKS5omT566Xc2FkAAhuMTVfaWRvYwASdWk6Ly9yYncxdHY5dGVsbG53AAhuMTZfZGY1cAAGc2xpZGVyAAVvaHhhbQAIbjE3X2RmNXAAA24xNwAFazQwdjEAB241X2s0MHYABmVmZmVjdAAIbjE4X2RmNXAAB2VmZmVjdDIACG4xOV9kZjVwAAtwcm9ncmVzc0JhcgAFdTd6YXAABWxvZ2luAAduNl9lbGxuAAJuNgADMjIyAAMzMzMACTEyMzEyMzIxMwAHbjhfYXZnNgAHbjlfYXZnNgAIbjExX2F2ZzYAA24xMQACdDAACUNvbWJvQm94MQASdWk6Ly9yYncxdHY5dHU3emF1AAZ2NnQzMTIACWxhYmVsdGVzdAAHbjBfdjZ0MwFQ6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSnAAduMV92NnQzAKjpmL/mlq/pob/mkpLlpKfmiYDlpKfpmL/mlq/pob/mkpLlpKfmiYDlpKfpmL/mlq/pob/mkpLlpKfmiYDlpKfpmL/mlq/pob/mkpLlpKfmiYDlpKfpmL/mlq/pob/mkpLlpKfmiYDlpKfpmL/mlq/pob/mkpLlpKfmiYDlpKfpmL/mlq/pob/mkpLlpKfmiYDlpKfpmL/mlq/pob/mkpLlpKfmiYDlpKcAB24yX3Y2dDMBUOmYv+aWr+mhv+aSkuWkp+aJgOWkp+mYv+aWr+mhv+aSkuWkp+aJgOWkp+mYv+aWr+mhv+aSkuWkp+aJgOWkp+mYv+aWr+mhv+aSkuWkp+aJgOWkp+mYv+aWr+mhv+aSkuWkp+aJgOWkp+mYv+aWr+mhv+aSkuWkp+aJgOWkp+mYv+aWr+mhv+aSkuWkp+aJgOWkp+mYv+aWr+mhv+aSkuWkp+aJgOWkp+mYv+aWr+mhv+aSkuWkp+aJgOWkp+mYv+aWr+mhv+aSkuWkp+aJgOWkp+mYv+aWr+mhv+aSkuWkp+aJgOWkp+mYv+aWr+mhv+aSkuWkp+aJgOWkp+mYv+aWr+mhv+aSkuWkp+aJgOWkp+mYv+aWr+mhv+aSkuWkp+aJgOWkp+mYv+aWr+mhv+aSkuWkp+aJgOWkp+mYv+aWr+mhv+aSkuWkp+aJgOWkpwAHbjNfdjZ0MwFQ6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSnAAduNF92NnQzAAJuNAFQ6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSn6Zi/5pav6aG/5pKS5aSn5omA5aSnAAduNV92NnQzAJHpmL/ovr7okKjovr5bYl3pmL/mlq/pob/mkpLml6ZbL2JdW2ld6Zi/5pav6aG/5pKS5pemWy9pXVt1XeaSkuWkp+WjsOWcsOaSklsvdV1baW1nXXVpOi8vcmJ3MXR2OXRvaHhhbVsvaW1nXVtjb2xvcj0jMDBmZjk5XemYv+iQqOW+t+Wkp+aJgFsvY29sb3JdAAZnMnU3MTQABC9wMi8ACmcydTcxNC5wbmcACW9oeGFtLnBuZw==";

export class package1_mainhud_data extends BaseView{
	public n7 : fgui.GComboBox;
	public n8 : fgui.GSlider;
	public n9 : fgui.GList;
    constructor()
    {
        super();
        this.package = "package1";
        this.packageItem = "mainhud";
        this.binData = __package1_Data;

        this.OnInit();
    }

    public OnInit():void
    {
        super.OnInit();
		this.n7 = <fgui.GComboBox><unknown>(this.getChild("n7"));
		this.n8 = <fgui.GSlider><unknown>(this.getChild("n8"));
		this.n9 = <fgui.GList><unknown>(this.getChild("n9"));
    }
}

export class package1_testui_data extends BaseView{
	public abilityImage : fgui.GDOTAAbilityImage;
	public avatarImage : fgui.GDOTAAvatarImage;
	public heroImage : fgui.GDOTAHeroImage;
	public itemImage : fgui.GDOTAItemImage;
	public userName : fgui.GDOTAUserName;
	public model : fgui.GDOTAScenePanel;
	public toggleButton : fgui.GComponent;
	public dropdown : fgui.GComboBox;
	public input : fgui.GTextInput;
	public richbox : fgui.GRichTextField;
	public n13 : fgui.GTextField;
	public n14 : fgui.GTextField;
	public list : fgui.GList;
	public slider : fgui.GSlider;
	public n17 : fgui.GImage;
	public effect : fgui.GDOTAScenePanel;
	public effect2 : fgui.GDOTAScenePanel;
	public progressBar : fgui.GProgressBar;
    constructor()
    {
        super();
        this.package = "package1";
        this.packageItem = "testui";
        this.binData = __package1_Data;

        this.OnInit();
    }

    public OnInit():void
    {
        super.OnInit();
		this.abilityImage = <fgui.GDOTAAbilityImage><unknown>(this.getChild("abilityImage"));
		this.avatarImage = <fgui.GDOTAAvatarImage><unknown>(this.getChild("avatarImage"));
		this.heroImage = <fgui.GDOTAHeroImage><unknown>(this.getChild("heroImage"));
		this.itemImage = <fgui.GDOTAItemImage><unknown>(this.getChild("itemImage"));
		this.userName = <fgui.GDOTAUserName><unknown>(this.getChild("userName"));
		this.model = <fgui.GDOTAScenePanel><unknown>(this.getChild("model"));
		this.toggleButton = <fgui.GComponent><unknown>(this.getChild("toggleButton"));
		this.dropdown = <fgui.GComboBox><unknown>(this.getChild("dropdown"));
		this.input = <fgui.GTextInput><unknown>(this.getChild("input"));
		this.richbox = <fgui.GRichTextField><unknown>(this.getChild("richbox"));
		this.n13 = <fgui.GTextField><unknown>(this.getChild("n13"));
		this.n14 = <fgui.GTextField><unknown>(this.getChild("n14"));
		this.list = <fgui.GList><unknown>(this.getChild("list"));
		this.slider = <fgui.GSlider><unknown>(this.getChild("slider"));
		this.n17 = <fgui.GImage><unknown>(this.getChild("n17"));
		this.effect = <fgui.GDOTAScenePanel><unknown>(this.getChild("effect"));
		this.effect2 = <fgui.GDOTAScenePanel><unknown>(this.getChild("effect2"));
		this.progressBar = <fgui.GProgressBar><unknown>(this.getChild("progressBar"));
    }
}

export class package1_login_data extends BaseView{
	public n6 : fgui.GComboBox;
	public n7 : fgui.GSlider;
	public n8 : fgui.GList;
	public n9 : fgui.GGraph;
	public n11 : fgui.GComponent;
	public t0 : fgui.Transition;
    constructor()
    {
        super();
        this.package = "package1";
        this.packageItem = "login";
        this.binData = __package1_Data;

        this.OnInit();
    }

    public OnInit():void
    {
        super.OnInit();
		this.n6 = <fgui.GComboBox><unknown>(this.getChild("n6"));
		this.n7 = <fgui.GSlider><unknown>(this.getChild("n7"));
		this.n8 = <fgui.GList><unknown>(this.getChild("n8"));
		this.n9 = <fgui.GGraph><unknown>(this.getChild("n9"));
		this.n11 = <fgui.GComponent><unknown>(this.getChild("n11"));
		this.t0 = this.getTransition("t0");
    }
}

export class package1_ComboBox1_data extends BaseView{
	public button : fgui.Controller;
	public n0 : fgui.GGraph;
	public n1 : fgui.GGraph;
	public n2 : fgui.GGraph;
	public title : fgui.GTextField;
    constructor()
    {
        super();
        this.package = "package1";
        this.packageItem = "ComboBox1";
        this.binData = __package1_Data;

        this.OnInit();
    }

    public OnInit():void
    {
        super.OnInit();
		this.button = this.getController("button");
		this.n0 = <fgui.GGraph><unknown>(this.getChild("n0"));
		this.n1 = <fgui.GGraph><unknown>(this.getChild("n1"));
		this.n2 = <fgui.GGraph><unknown>(this.getChild("n2"));
		this.title = <fgui.GTextField><unknown>(this.getChild("title"));
    }
}

export class package1_labeltest_data extends BaseView{
	public n0 : fgui.GTextField;
	public n1 : fgui.GTextField;
	public n2 : fgui.GTextField;
	public n3 : fgui.GTextField;
	public n4 : fgui.GTextField;
	public n5 : fgui.GRichTextField;
    constructor()
    {
        super();
        this.package = "package1";
        this.packageItem = "labeltest";
        this.binData = __package1_Data;

        this.OnInit();
    }

    public OnInit():void
    {
        super.OnInit();
		this.n0 = <fgui.GTextField><unknown>(this.getChild("n0"));
		this.n1 = <fgui.GTextField><unknown>(this.getChild("n1"));
		this.n2 = <fgui.GTextField><unknown>(this.getChild("n2"));
		this.n3 = <fgui.GTextField><unknown>(this.getChild("n3"));
		this.n4 = <fgui.GTextField><unknown>(this.getChild("n4"));
		this.n5 = <fgui.GRichTextField><unknown>(this.getChild("n5"));
    }
}

