import * as fgui from "panorama-fgui-types/fgui/FairyGUI";
import { BaseView } from "../BaseView";
import { BinCache } from "../BinCache";
export class test_vipView_data extends BaseView{
	public n1 : fgui.GGraph;
	public titleLabel : fgui.GTextField;
	public testBtn : fgui.GButton;
    constructor()
    {
        super();
        this.package = "test";
        this.packageItem = "vipView";

        this.OnInit();
    }

    public OnInit():void
    {
        super.OnInit();
		this.n1 = <fgui.GGraph><unknown>(this.getChild("n1"));
		this.titleLabel = <fgui.GTextField><unknown>(this.getChild("titleLabel"));
		this.testBtn = <fgui.GButton><unknown>(this.getChild("testBtn"));
    }
}


BinCache.PrecachePackage("test", "RkdVSQAAAAYAAAh0dTJtcncweQAEdGVzdAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAaAAAAHgAAA+sAAAAAAAAD7QAAAAAAAAAAAAIAAAI2AwAAAAEAAv/+AAAAAGQAAAAUDAAAAhsIAAAAACIAAAAvAAAAUwAAAfkAAAH6AAACDQAAAg8AAAAAAAAAZAAAABQAAAAAAAABACADAQAIAAsAHgADAAAEAAQABQAGAAcACAAJAAoACwAAAAAEAGMHAQAQAD0AQQBNAAAAVQBjA//+//4ADAANAAAAAAAAAAABAAAAZAAAABQAAAAAP4AAAAAAAAABAAAAAP/+//7//wABAAgAAAAAAQAEAAH//wIOAA8AAQAAAAAAAAD/8PDw/wAAYwcBABAAPQBBAE0AAABVAGMD//7//gAOAA8AAAAAAAAAAAEAAABkAAAAFAAAAAA/gAAAAAAAAAEAAAAA//7//v//AAEACAAAAAABAAgAAf//Ag4ADwABAAAAAAAAAP/6+vr/AABlBwEAEAA9AEEATwAAAFcAZQP//v/+ABAAEQAAAAAAAAAAAQAAAGQAAAAUAAAAAD+AAAAAAAAAAQAAAAD//v/+//8AAQAKAAAAAAIABgAKAAH//wIOAA8AAQAAAAAAAAD/zMzM/wAAcQcBABAAPQBBAEMAAABLAG8G//7//gASABMAAAAAAAAAAAEAAABkAAAAFAAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAB//8CDgAPAP/+ABgAAAD/AQEAAwAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAP/+AP/+Af////4AAAAAAAAAAP/+//4AAAD//j+AAAAAP0zMzf/+AAAAAAGNAwAUABUAFv/+AQAAB4AAAAQ4AAAAAXIIAAAAACIAAAAvAAAAMQAAAVwAAAFdAAABcAAAAAAAAAAAAAAHgAAABDgAAAAAAAAAAAMAUgcBABAAPQBBAEMAAABEAFID//7//gAOAA8AAAAAAAAAAAEAAAeAAAAEOAAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAAAQAAAAEAAAD/MzMz/wAAcQcBABAAPQBBAEMAAABLAG8G//7//gAMABcAAAOGAAAAAAEAAAB0AAAASgAAAAA/gAAAAAAAAAEBAAAA//7//v//AAAB//8CAwAHAP/+ADgAAAD/AQAAAwAAAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAYAGAHAQAQAD0AQQBDAEQASgBKCQAA//4AEAAZAAAC7wAAAr4BAAABoQAAAK8AAAAAP4AAAAAAAAABAQAAAP/+//7//wAAAP//AAAAAAwAGv/+//7//gAAAAAA/////v/+AAAA//4B/////gAAAAAAAAAA//7//gAA//4AAAAAAAAAGwAFOGVkcTEAB0J1dHRvbjEAAS8ABmJ1dHRvbgABMAACdXAAATEABGRvd24AATIABG92ZXIAATMADHNlbGVjdGVkT3ZlcgAHbjBfOGVkcQACbjAAB24xXzhlZHEAAm4xAAduMl84ZWRxAAJuMgAHbjNfOGVkcQAFdGl0bGUABThlZHEwAAd2aXBWaWV3AAcvdmlld3MvAAp0aXRsZUxhYmVsAAbmoIfpopgAB3Rlc3RCdG4AD+Wlpeacr+Wkp+W4iOWkmg==");
